import Head from 'next/head'

const Layout = ({ children }) => {
  
  return (
      <div>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#ee6380"/>
        <meta name="apple-mobile-web-app-title" content="MiamiCoin UI"/>
        <meta name="application-name" content="MiamiCoin UI"/>
        <meta name="msapplication-TileColor" content="#000000"/>
        <meta name="theme-color" content="#ffffff"/>
      </Head>
        {children}
      </div>
  );
};

export default Layout;